import 'package:project_travelapp_app/models/hotelModel.dart';

List<List>difhot=[
  [
    HotelClass(
      name: 'Hotel Druk',
      abt: '+975-17262782',
      price: 'Nu.2300',
      imgurl: 'assets/images/THD1.webp',
      imgurl2: 'assets/images/THD2.jpg',
      imgurl3: 'assets/images/THD3.jpg',
      location: 'Thimphu,Bhutan',
      review: '',
    ),
    HotelClass(
      name: 'Le Meridian',
      abt: '+975-1726282',
      price: 'Nu.3500',
      imgurl: 'assets/images/TL1.webp',
      imgurl2: 'assets/images/TL2.webp',
      imgurl3: 'assets/images/TL3.webp',
      location: 'Thimphu,Bhutan',
      review: '',
    ),
    HotelClass(
      name: 'lemon Tree',
      abt: '+975-17265782',
      price: 'Nu.3000',
      imgurl: 'assets/images/TLem1.webp',
      imgurl2: 'assets/images/TLem2.webp',
      imgurl3: 'assets/images/TLem3.webp',
      location: 'Thimphu,Bhutan',
      review: '',
    ),
    HotelClass(
      name: 'Pemako Thimphu',
      abt: '+975-17232782',
      price: 'Nu.2500',
      imgurl: 'assets/images/TP1.webp',
      imgurl2: 'assets/images/TP2.webp',
      imgurl3: 'assets/images/TP3.webp',
      location: 'Thimphu,Bhutan',
      review: '',
    ),

  ],
  [
    HotelClass(
      name: 'Hotel Kingacholing',
      abt: '+975-16262781',
      price: 'Nu.1200',
      imgurl: 'assets/images/GK1.jpg',
      imgurl2: 'assets/images/GK2.jpg',
      imgurl3: 'assets/images/GK3.jpg',
      location: 'Gelephu,Bhutan',
      review: '',
    ),
    HotelClass(
      name: 'Kuku Grand Hotel',
      abt: '+975-77252182',
      price: 'Nu.3500',
      imgurl: 'assets/images/GKu1.jpg',
      imgurl2: '',
      imgurl3: '',
      location: 'Gelephu,Bhutan',
      review: '',
    ),


  ],
  [
    HotelClass(
      name: 'Dhensa Bontique',
      abt: '+975-77262782',
      price: 'Nu.3500',
      imgurl: 'assets/images/PD1.webp',
      imgurl2: 'assets/images/PD2.webp',
      imgurl3: 'assets/images/PD3.webp',
      location: 'Punakha,Bhutan',
      review: '',
    ),
    HotelClass(
      name: 'Hotel Lopesa',
      abt: '+975-16762782',
      price: 'Nu.2000',
      imgurl: 'assets/images/PHL1.webp',
      imgurl2: 'assets/images/PHL1.webp',
      imgurl3: 'assets/images/PHL1.webp',
      location: 'Punakha,Bhutan',
      review: '',
    ),
    HotelClass(
      name: 'Hotel Zhimkhang',
      abt: '+975-17442782',
      price: 'Nu.2300',
      imgurl: 'assets/images/PHZ1.webp',
      imgurl2: 'assets/images/PHZ2.webp',
      imgurl3: 'assets/images/PHZ3.webp',
      location: 'Punakha,Bhutan',
      review: '',
    ),
    HotelClass(
      name: 'The Four Bontique',
      abt: '+975-17442582',
      price: 'Nu.3000',
      imgurl: 'assets/images/PTF1.webp',
      imgurl2: 'assets/images/PTF2.webp',
      imgurl3: 'assets/images/PTF3.webp',
      location: 'Punakha,Bhutan',
      review: '',
    ),

  ],
  [
    HotelClass(
      name: 'Dewachen Hotel & Spa',
      abt: '975-17123782',
      price: 'Nu.2000',
      imgurl: 'assets/images/PDH1.jpg',
      imgurl2: 'assets/images/PDH2.jpg',
      imgurl3: 'assets/images/PDH3.jpg',
      location: 'Bhumthang,Bhutan',
      review: '',
    ),
    HotelClass(
      name: 'Metta Resort & Spa',
      abt: '975-174425541',
      price: 'Nu.3500',
      imgurl: 'assets/images/PMR1.jpg',
      imgurl2: 'assets/images/PMR1.jpg',
      imgurl3: 'assets/images/PMR1.jpg',
      location: 'Bhumthang,Bhutan',
      review: '',
    ),
    HotelClass(
      name: 'Naksel Hotel & Spa',
      abt: '975-1744275',
      price: 'Nu.3000',
      imgurl: 'assets/images/PNH1.webp',
      imgurl2: 'assets/images/PNH2.webp',
      imgurl3: 'assets/images/PNH3.webp',
      location: 'Bhumthang,Bhutan',
      review: '',
    ),
    HotelClass(
      name: ' Tashi Namgyal Resort',
      abt: '975-17242782',
      price: 'Nu.4000',
      imgurl: 'assets/images/PTN1.webp',
      imgurl2: 'assets/images/PTN2.webp',
      imgurl3: 'assets/images/PTN3.webp',
      location: '',
      review: '',
    ),

  ],
  [
    HotelClass(
      name: 'Amkora Resort',
      abt: '975-16242782',
      price: 'Nu.3500',
      imgurl: 'assets/images/BA1.webp',
      imgurl2: 'assets/images/BA2.webp',
      imgurl3: 'assets/images/BA3.webp',
      location: 'Bhumthang,Bhutan',
      review: '',
    ),
    HotelClass(
      name: 'Hotel Ugyenling',
      abt: '975-17672565',
      price: 'Nu.3000',
      imgurl: 'assets/images/BHU1.webp',
      imgurl2: 'assets/images/BHU1.webp',
      imgurl3: 'assets/images/BHU1.webp',
      location: 'Bhumthang,Bhutan',
      review: '',
    ),
    HotelClass(
      name: 'Valley Resort',
      abt: '975-174427826',
      price: 'Nu.2000',
      imgurl: 'assets/images/BVR1.webp',
      imgurl2: 'assets/images/BVR2.webp',
      imgurl3: 'assets/images/BVR3.webp',
      location: 'Bhumthang,Bhutan',
      review: '',
    ),
    HotelClass(
      name: 'Hotel Yugharling',
      abt: '975-174427565',
      price: 'Nu.2000',
      imgurl: 'assets/images/BHY1.webp',
      imgurl2: 'assets/images/BHY2.webp',
      imgurl3: 'assets/images/BHY3.webp',
      location: 'Bhumthang,Bhutan',
      review: '',
    ),

  ],

];

